services:
  redis:
    image: redis:8.0
    ports:
      - "6379:6379"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAX_CONCURRENT_SESSIONS=1
      - MAX_LIFETIME_SESSIONS=10
    ports:
      - "8080:8080"
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=3131
      - PRIVATE_HOSTNAME=worker
    depends_on:
      - redis
    restart: unless-stopped
